# -*- coding: utf-8 -*-
"""
Created on Tue Jun 30 18:17:05 2020

@author: Nikhil Mathur
"""
print("please enter first word capital")
x=input("search recipie : ")
print("\n")
if (x=='Jeera rice'):
    print("Ingredients1 cup Basmati rice (a long grain Indian rice) \n 3 cups water \n Salt to tast \n 2 tablespoons vegetable, sunflower or canola oil/ghee  \n 1 large onion (finely chopped) \n 2 teaspoons cumin seeds \n 1/2 cup waterCoriander leaves to garnish")
    print("Steps to Make It\nWash the Basmati rice well in running water.\nAdd the 3 cups of water and salt to taste to the rice and set it up to boil.\nOnce the rice is almost cooked (test a few grains often to check—they will feel soft on the outside but very slightly hard on the inside), remove from fire and drain the water by straining the rice through a sieve or colander. Set aside.\nIn another pan, heat the oil/ghee till hot and add onions.\nFry till light brown and then add the cumin seeds. The seeds will splutter and sizzle to show they are done.\nNow add the rice and stir well.\nAdd 1/2 a cup of water to the rice and cover.\nSimmer till all the water dries up.\nAllow the rice to stand for another 2 to 3 minutes and then serve garnished with coriander leaves.\nEnjoy!")
elif(x=="Mutter paneer"):
    print("Ingredients\n large onions (cut into quarters)\n3 medium-sized tomatoes (cut into quarters)\n6 tablespoons vegetable oil (or canola or sunflower cooking oil, divided)\n1 pound paneer (cubed)\n1 tablespoon ginger paste\n2 tablespoons garlic paste\n\n2 teaspoons coriander powder\n1 teaspoon cumin powder\n1/2 tsp turmeric powder\n2 teaspoons garam masala\n2 green chillies (finely chopped)\n1/2 pound shelled peas\n1 1/2 cups water (hot)\nSalt (to taste)\n3 tablespoons heavy cream\nGarnish: 1/3 cup fresh coriander leaves (finely chopped)\n")
    print("Steps to Make It\nGather the ingredients.\nIngredients for mutter paneer peas cottage cheese\nGrind the onions into a fine paste in a food processor. Keep aside.Grind\nNext grind tomatoes into a fine paste and keep aside.Grind the tomatoes\nHeat 2 to 3 tablespoons of the vegetable oil in a deep pan and gently stir-fry the cubes of paneer till golden.\nHeat vegetable oil in a pan\nWhen golden, remove onto a paper towel and keep aside.\nPut on paper towel\nIn the same vessel, heat the remaining 2 to 3 tablespoons of the vegetable oil and add the onion paste. Fry till it turns light brown. You will need to stir frequently to avoid the paste burning. Also, do not over-fry as it will turn bitter and ruin the curry. Another hassle-free way to do this is to chop the onions fine and then sauté till pale golden, then grind in the food processor.\nHeat vegetable oil\nWhen the onion paste is fried, add tomato paste, ginger and garlic paste, and sauté for another 2 minutes.\nOnion pasteNext, add the coriander, cumin, turmeric, and garam masala powders, and the finely chopped green chilies and sauté, stirring continuously, till the cooking oil begins to separate from the masala (spice mixture).Add coriander, cumin, tumeric\nNow add the peas to the masala and fry for 2 to 3 minutes.\nAdd the peasThen add the previously fried paneer, hot water, and salt, to taste, reduce the heat to a simmer and cook till the gravy thickens.\nAdd paneerWhen the gravy is as thick as you would like, turn off the heat and stir in the cream.\nTurn off heatGarnish with coriander leaves and serve with chapati, paratha, naan, or jeera rice.\n")
elif(x=='Tea'):
    print('Ingredients\n1/2 teaspoon turmeric powder\n2 cups water\n1/2 cup milk (soy or dairy)\n1 tablespoon almond oil\nOptional: 1 teaspoon honey (or agave nectar or maple syrup, to taste))\n')
    print("Steps to Make It\n1 Bring water to a boil and add turmeric.\n2 Allow to simmer for 8-10 minutes, stirring to make sure the turmeric is fully dissolved. Reduce heat, add milk and oil and stir well.\n3 Add sweetener if desired and enjoy!\n")
elif(x=="Rajma"):
    print("Ingredients\n2 tablespoons oil (vegetable, canola, or sunflower cooking oil)\n1 teaspoon cumin seeds\n2 medium onions (chopped finely)\n2 inches ginger (julienned)\n6 cloves garlic (minced)\n2 green chilies (fresh, chopped fine)\n2 large tomatoes (chopped into 1-inch cubes)\n2 teaspoons coriander (powder)\n1 teaspoon cumin (powder)\n1 teaspoon garam masala\n1/4 teaspoon turmeric (powder)\n2 (15.5 ounce) cans red kidney beans (drained, rinsed under running water)\n3 cups water (warm)\nSalt to taste1 pinch of asafetida\nGarnish: coriander (chopped)")
    print("Steps to Make It\n take a deep pan, heat the oil and add the cumin seeds. When they stop sizzling, add the onion and fry until soft.\nAdd the ginger and garlic and fry for 2 minutes.\nAdd the green chilies, tomatoes, coriander, cumin, turmeric, and garam masala and fry until the oil separates from the masala.\ndd the red kidney beans, warm water, and asafetida, as well as the salt to taste. Cook until the beans are soft, approximately 10 minutes.\nMash some of the beans roughly to thicken the sauce\n.Garnish with coriander and serve hot with rice, Kachumbar salad, and the pickle of your choice.")
elif(x=='Chili paneer'):
    print("Ingredients\n ..........\n500 gms paneer/ cottage cheese (cut into 2-inch cubes)3 tbsp vegetable cooking oil\n2 large onions (sliced thinly)\n5 to 6 cloves of garlic (chopped very fine)\n1 medium bunch spring onion (chopped coarsely)\n3 tbsp tomato ketchup\n1 tbsp green/ red chili sauce\n2 tsp soy sauce\n1 tsp vinegar\n1 chicken stock cube\n1 large or 2 medium-sized green bell peppers/ capsicum pith seeds removed (discard) and cut into 2-inch square pieces\n")
    print("Steps to Make It\n.........\nGather the ingredients.eat the oil in a wok or deep pan on a medium to high heat.\nAdd the onion, garlic and spring onion (keep a little - 2 tbsps - aside for garnish later). Fry till soft.\nAdd all the sauces, vinegar and the chicken stock cube and cook for 2 minutes, stirring continuously.\nNow add the paneer and green bell peppers. Mix well and check for salt. Season if required. Cook for 1 more minute. This dish should have almost no gravy -\n just a coating sauce. If it is too dry, add 1/4 cup of water and mix well.\n Turn off the heat and spoon the chili paneer onto a serving platter.\nGarnish with some chopped spring onion and serve with toothpicks so everyone can help themselves.\n")
elif(x=='Paneer pakode'):
    print("Ingredients\n ..........\n 1 (250-gram) package Indian paneer cheese (sliced into 1/2-inch thick slices or cubes)\n1 cup chickpea flour (also called gram flour or besan)\n2 teaspoons high-heat cooking oil or ghee (Indian butter)\nOptional: 1/2 teaspoon garam masala\n1/2 teaspoon salt\n1/4 to 1/2 teaspoon cayenne pepper (to taste)\n1/3 to 1/2 cup water\nOil (for frying)\n")
    print('Steps to Make It......\nGather the ingredients.\nIngredients for fried paneer\nWhisk together the chickpea flour, oil or ghee, garam masala, salt, and chili powder. Slowly incorporate water, adding just enough to form a thick batter.\nWhisk together chickepea \nDip each paneer slice in batter, turning to coat well.\nDip paneer in batter\nFry in hot oil just until lightly golden brown.\nFry in oil\nThese fried paneer slices are best when they are fresh, so enjoy your paneer pakoras hot.\nServe paneer slices\n')
elif(x=='Kheer'):
    print('Ingredients\n.....................\n2 liters full-cream milk.\n1 can/400 grams sweetened condensed milk.\n1 tsp. cardamom powder.\n1 cup of sugar.\n1 cup Basmati rice.\n50 grams almonds blanched and slivered.\n50 grams raisins.\nA few strands of saffron.\nOptional: rose petals to garnish.\n')
    print('Steps to Make It\n.................\nWash the rice well and soak for half an hour in enough water to cover it fully.\nPut the milk, condensed milk and sugar in a deep, thick-bottomed pan and boil. When the milk comes to a boil, add the rice and simmer. Cook till the milk thickens and reduces to half its original volume.\nAdd the almonds, raisins, and cardamom and cook for 5 more minutes.\nTurn off the cooktop and add the saffron. Stir well.\nAllow the kheer to cool, then chill.\nServe cold garnished with rose petals.')
elif(x=='Rasgulla'):
    print('Ingredients\n..............\n 8 1/2 cups whole milk\n2 to 3 tablespoons lime juice (or lemon juice)\n5 teaspoons flour\n2 cups sugar\n4 cups water\n2 to 3 tablespoons rose water (or a few strands of saffron)\n')
    print('Steps to Make It\n..................\nGather the ingredients.\nBring the milk to a boil over a medium flame. Stir it occasionally to ensure the milk does not burn.\nBring milk to boil\nWhen the milk begins to boil, add the lime juice and mix well.\nAdd lime juice\nWhen the curds begin to separate from the milk, turn off the heat and leave the milk aside for 10 minutes to let the curdling process finish.\nCurds\nStrain the cheese and wash it well under running water. This will remove all the lime juice from it.\nStrain cheese\nNow put the cheese in a cheesecloth and hang it for 1 hour over a bowl to completely drain all the liquid from it.\nCheesecloth\nPut the drained cheese into a mixing bowl and begin to knead it.\nPut in bowl\nContinue until all of the lumps are removed and the cheese is absolutely smooth. When this happens the cheese will begin to release its fat and your hands will feel greasy. The success of your rasgulla-making effort depends on how smooth you knead the cheese, so give it your best shot!\nBall cheese curd\nNow sprinkle the flour over the surface of the cheese and work it into the cheese to mix thoroughly.\nSprinkle with flour\nMix the sugar and water in a pressure cooker and bring the mixture to a boil (without covering the pressure cooker). Make sure the cooker is large enough to accommodate the finished rasgullas, as they will expand to double their size while cooking in the syrup.\nMix sugar and water\nWhile the sugar syrup boils, divide the dough into small marble-sized balls and roll them between your palms till smooth.\nDivide dough into balls\nGently add the balls to the sugar syrup.\nAdd dough to water\nCover the pressure cooker, add the cooker weight, and wait for the first whistle.\nCover pressure cooker\nOnce the first whistle blows, wait another 8 to 10 minutes and then turn off.\nRelease the steam from the pressure cooker and allow the Rasgullas to cool completely before touching them. They will have expanded to almost double their original size and will be delicate when hot.\nAllow rasgulias to cool\nWhen they are cool, pour the rose water or saffron syrup (made by soaking the saffron strands in a little warm water) on the rasgullas.\nPour syrup over\nChill for a few hours before serving.')
elif(x=='Bhindi'):
    print('Ingredients\n..............\n About 1 pound okra (bhinidi)\nCooking oil for frying\n1/2 cup Bengal gram flour (besan)\n1/2 teaspoon turmeric powder\n1/2 teaspoon red chili powder\n1 teaspoon carom seeds (ajwain)\n4 teaspoons chaat masala\nSalt to taste\nJuice of 1 lime')
    print('Steps to Make It\n..................\nWash the okra and dry thoroughly. Remove the top stem of each and then cut lengthwise into thin slices.\nAdd 2 to 3 tablespoons of oil to a deep skillet and heat over medium heat.\nPut the okra in a large mixing bowl and sprinkle over all of the dry ingredients except the salt. Season with salt just before frying (or else the okra will release water and become soggy).\nDeep-fry the okra a few at a time until crisp. Remove and drain on paper towels. Repeat with remaining okra in batches, adding more oil as needed.\nGarnish with the lime juice and serve with plain boiled rice and your favorite daal.')
elif(x=='Pata gobhi'):
    print('Ingredients\n.................\n1 medium/250-300 gram cabbage (sliced very thinly)\nOptional: 2 medium potatoes (quartered lengthwise and then sliced thinly)\nOptional: 1 cup frozen peas (or fresh peas)\n2 tbsps vegetable/canola/sunflower cooking oil\nn5-6 curry leaves\n1/2 tsp. mustard seeds\n2 green chilies (chopped fine)\n2-inch piece ginger (grated)\n2 large tomatoes (cut into 1-inch cubes)\n1/2 tsp turmeric powder\n1 tsp coriander powder\n1 tsp cumin powder\n1 tsp red chili powder (use less for less spicy)\nSalt to taste\nFresh coriander for garnish (chopped)\n........\nSteps to Make It\n..........\nGather the ingredients.\nHeat the oil in a pan on a medium flame. Add the mustard seeds, green chilies, curry leaves and fry till the seeds stop spluttering.\nAdd the ginger and stir. Add the tomatoes and cook till they are pulpy.\nIf you are using peas and potatoes, add them now. Cook for 4-5 minutes. Add the cabbage and then the turmeric, coriander, cumin, red chili powder and salt to taste. Mix well.\nCover, simmer and cook for 10 minutes.\nGarnish with freshly chopped coriander and serve with hot Chapatis (Indian flatbread) and a tangy pickle.')
elif(x=='Dosa'):
    print("Ingredients\n......................\n 3 cups rice\n 1 cup urad dal (split, skinless black gram)\n3/4 teaspoon fenugreek seeds \nSalt, to taste\nGhee (or vegetable, canola, or sunflower oil)\n Steps to Make It\n ...........................\nGather the ingredients.\nDosas ingredientsWash the rice and urad dal well.\n Add the fenugreek seeds to the mix and add enough water to the bowl to cover the mixture by about 2 inches. Soak overnight.\nSoaking rice for dosasThe next morning, drain all the water from the rice mixture. \nAdd to the food processor and process—adding very little water if needed—until a smooth yet slightly grainy paste has formed.Rice in a food processorTransfer to a large mixing bowl and gradually add enough water to make a batter. The consistency of the batter should be such that it thinly coats a spoon dipped in it.Rice-daal mixture in a bowlAdd salt to taste and keep the dosa batter aside in a warm, dark spot, covered, for 12 to 24 hours. After this fermentation, stir the batter well. It will have thickened to coat a spoon thickly. It is now ready to make dosas.Dosa batter in a bowlPut some ghee or oil in a small bowl and keep ready. You will also need a small bowl of ice-cold water, a large, flat nonstick pan, paper towels, a ladle, a spatula, and a basting brush.Fold one sheet of paper towel into a thick rectangle and dip lightly into the bowl of cooking oil.\n Squeeze out any excess and then rub the paper towel all over the surface of the pan to lightly grease. The ghee or oil should barely be visible in the pan. Turn on the heat to medium-high.Add a scant ladleful of batter to the center of the pan, much like you would for a pancake.Dosa batter in a panBegin to spread the batter in sweeping circular motions to form a pancake of roughly 8-inch diameter. Do not be alarmed if the dosa develops tiny holes as you spread the batter. This is normal.Swirling dosa batter in a panAs soon as you have finished spreading the batter out on the pan, dip the basting brush in ghee and drizzle all over the surface of the dosa and also around its edges. \n Hold the pan by its handle, lift it up, and swirl it so that the drizzled ghee spreads all over the dosa.​When the upper surface begins to look cooked (it will no longer look soft or runny), flip the dosa. \n By this time, the surface that was underneath should be light golden in color. Cook for 1 minute after flipping.\nThe dosa is almost done. Fold it in thirds like a parcel and allow to cook for 30 seconds more.Folded dosaBefore you start making the next dosa, fold another sheet of paper towel into a wad and dip it in ice-cold water. Squeeze to remove excess water and then rub it all over the surface of the pan to cool it slightly. This ensures your next dosa will spread evenly and not break because the pan is too hot.Homemade dosasRepeat until you've made enough dosas. Any leftover batter can be refrigerated, tightly covered, for up to three days.")
elif(x=="Mangodi"):
    print('Ingredients\n............\nसामग्रीएक छोटी कटोरी मूंग दाल | nएक बड़ा चम्मच लहसुन-अदरक का पेस्ट\nदो हरी मिर्च बारीक कटी हुई \nआधा छोटा चम्मच लाल मिर्च पाउडर\nआधा कप हरा धनिया बारीक कटा\nचुटकीभर हींग\nएक छोटा चम्मच गरम मसाला पाउडर\nनमक स्वादानुसार \nतेल जरूरत के अनुसार \n')
    print("विधि-\n.................\nसबसे पहले मूंग दाल को साफ करके धो लें और इसे एक बर्तन में 7 से 8 घंटे के लिए पानी में भिगोकर रख दें। तय समय के बाद पानी निकालकर मूंग दाल को अच्छे से पीस लें। ध्यान रखें कि दाल का पेस्ट गाढ़ा हो। अब दाल के पेस्ट में हींग, लाल मिर्च पाउडर, गरम मसाला पाउडर, अदरक-लहसुन का पेस्ट, हरी मिर्च, हरा धनिया और नमक डालकर मिक्स कर लें। मीडियम आंच में एक पैन में तेल गरम करें।  तेल के गरम होते ही दाल का मिश्रण लेकर गोलाकार में पकौड़े बनाते हुए तेल में डालें और सुनहरा होने तक तल लें। सभी पकौड़ों के तलने के बाद आंच बंद कर दें। आपकी मूंग दाल की मंगौड़ी बनकर तैयार है। इसे हरे धनिये की चटनी के साथ सर्व करें। ")
elif(x=='Sev tamatar'):
    print("आवश्यक सामग्री\n................\nबेसन- 1 कप \nटमाटर- 4 (बारीक कटे हुए)\nतेल- 3 बड़े चम्मच\nकाली सरसो के दाने- ½ छोटी चम्मच\nजीरा- ½ छोटी चम्मच\nहींग- ½ चुटकी\nहल्दी पाउडर- ½ छोटी चम्मच\nहरी मिर्च- 2 (बारीक कटी हुई)\nअदरक- 1 इंच (ग्रेट किया हुआ)\nधनिया पाउडर- 1 छोटी चम्मच\nलाल मिर्च पाउडर- 1 छोटी चम्मच\n गरम मसाला- ¼ छोटी चम्मच \nनमक- 1 छोटी चम्मच \nहरा धनिया- गार्निशिंग के लिए\nतेल- तलने के लिए\n")
    print("विधि\n..........\nसेव टमाटर की सब्जी बनाने के लिए सबसे पहले हम सेव बना लेगें सेव बनाने के लिए एक बर्तन में 1 कप बेसन  ¼ छोटी चम्मच नमक और 1 छोटी चम्मच तेल ले कर सभी चीजो को अच्छे से मिला लीजिए। सभी चीजों को मिला लेने के बाद थोड़ा-थोड़ा पानी डालते हुए सोफ्ट आटा गूंथ लीजिए। इतना आटा गूंथने में ¼ कप पानी लगा है। अब सेव तलने के लिए एक कढ़ाई में तेल गर्म कर लीजिए।तेल के गर्म हो जाने के बाद तेल में थोड़ा सा आटा डाल कर तेल का तापमान चेक कर लीजिए। अगर आटा डालने पर वो तल कर ऊपर आ जाता है तो सेव तलने के लिए तेल अच्छा गर्म हो गया है। अब एक कलछी ले कर उस पर थोडा-सा आटा डाल कर हाथ से दबाते हुए मल-मल कर कढ़ाई में सेव बना लीजिए। सेव को 1-2 मिनट बाद कलछी से अलग करते हुए गोल्डन ब्राउन हाेने तक तल लीजिए। बेसन के सारे आटे के इसी तरह से सेव बना लीजिए।अब एक कढ़ाई में 2-3 बड़ी चम्मच तेल डाल कर गर्म कर लीजिए। \n")
    print("तेल के हल्के गर्म हो जाने पर इसमें ½ छोटी चम्मच काली सरसो के दाने, ½ छोटी चम्मच जीरा डाल कर भून लीजिए। जीरा हल्का सा भुन जाने पर इसमें ½ चुटकी हींग, ½ छोटी चम्मच हल्दी पाउडर, 2 हरी मिर्च, 1 इंच अदरक डाल कर मीडियम आंच पर हल्का सा भून लीजिए। मसालो के भुन जाने के बाद इसमें 4 कटे हुए टमाटर, 1 छोटी चम्मच धनिया पाउडर, 1 छोटी चम्मच लाल मिर्च पाउडर और ¾ छोटी चम्मच नमक डाल कर टमाटर के नर्म होने तक पका लीजिए। अब टमाटर को ढक कर 3 मिनट तक नर्म होने तक पकने दीजिए। 3 मिनट बाद टमाटर को हल्का सा मैश करते हुए चला लीजिए। टमाटर के मैश हो जाने पर इसमे 1 कप पानी डाल कर उबाल लीजिए।मसाले में उबाल आ जाने पर इसमें 1 कप सेव, ¼ छोटी चम्मच गरम मसाला और थोड़ा सा हरा धनिया डाल कर मिला लीजिए और ढक कर 6-7 मिनट तक पकने दीजिए।7 मिनट बाद सब्जी को किसी बर्तन में निकाल कर ऊपर से गार्निशिंग के लिए हरा धनिया डाल कर सर्व कर सकते है। आप इस सब्जी को रोटी, पराठा या चावल के साथ खा सकते है।")
elif(x=="Dum aloo"):
    print("आवश्यक सामग्री \n............\nआलू - 4 (400 ग्राम)\nटमाटर -  6 (400 ग्राम)\nहरी मिर्च - 2\nअदरक - 1 इंच टुकडा़\nपनीर - 150 ग्राम\nतेल - 4-5 टेबल स्पून\nकाजू - ¼ कप और 4 काजू बारीक कटे हुए\nहरा धनिया 2-3 टेबल स्पून (बारीक कटा हुआ)\nअदरक - 1 छोटी चम्मच (बारीक कटा हुआ)\nमैदा - 2 चम्मच  \nहरी मिर्च - 1 (बारीक कटी हुई)\nजीरा - ½ छोटी चम्मच\nहल्दी पाउडर - ½ छोटी चम्मच\nधनिया पाउडर -1.5 छोटी चम्मच\nलाल मिर्च पाउडर - 1 छोटी चम्मच\nकसूरी मेथी - 2 छोटी चम्मच\nकिशमिश - 15\nदालचीनी - 1.25 इंच टुकड़ा\nलौंग - 4\nकाली मिर्च - 8\nसाबुत बड़ी इलायची - 1\nनमक - 1.5 छोटी चम्मच  \n")
    
elif(x=='Poha'):
    print("आवश्यक सामग्री...\n...................\nपोहे -150 ग्राम (2 1/2 कप) beaten rice or Flattened rice\nचीनी - 1 चम्मच\nनमक स्वादानुसार (3/4छोटी चम्मच)\nतेल -  1-2 टेबल स्पून\nराई - 1/4 छोटी चम्मच\nकरी पत्ता - 6-7\nहल्दी पाउडर  - 1/4 छोटी चम्मच\nहरी मिर्च -1 -2\nमटर के दाने या मूंगफली के दाने - 1 -2  टेबल स्पून\nनींबू -एक\nहरा धनिया - एक टेबल स्पून बारीक कटा हुआ\nकिशमिश - 20 - 25 (यदि आप चाहें)\nबेसन के पतले सेब- एक छोटी प्याली\n")
    print("How To Make Poha\n.........................\nपोहा साफ कर लीजिये.  पोहे को थाली में डालिये और इसमें पानी डाल कर पानी को तुरन्त निकाल दीजिये जैसे कि पोहे को धो रहे हैं, या पोहे को छलनी में लेकर, पोहे के ऊपर से एक बड़ा प्याला पानी डाल दीजिये,  सारा पानी निकलने के बाद. भीगे हुये पोहे में एक चम्मच चीनी एवं नमक मिला कर 15 मिनिट के लिये फरैरा करने के लिये रख दीजिये.हरी मिर्च के डंठल तोड़िये, धोइये और छोटा छोटा काट लीजिये.  हरी मटर के दाने निकाल लीजिये, और हरा धनियाँ बारीक काट कर तैयार कर लीजिये.  एक प्याले में बेसन के बीकानेरी पतले सेव रख लीजिये. एक प्याले में तले हुये मूंगफली के दाने भी हो तो वह भी पोहा के ऊपर डाले जा सकते हैं.कढा़ई को गैस पर रखे़ और उसमें तेल डाल कर गरम कीजिये.  तेल गरम होने पर राई के दाने डालिये, दाने कढ़कढाहट के साथ भुनने लगेंगे, करी पत्ता डाल दीजिये,  इसमें कटे हुये मिर्च और हल्दी पाउडर डालिये, मटर के दाने भी इस तेल में डाल कर भून लीजिये,  इस मसाले में भीगा हुआ पोहा और किशमिश डाल कर, पोहे पर हल्दी की कोटिंग अच्छी तरह आने तक मिला दीजिये, आग बन्द कर दीजिये और नीबू का रस और कतरा हुआ आधा हरा धनियां मिला दीजिये. लीजिये स्वादिष्ट पोहा बनकर तैयार है़.पोहा को प्याले में निकाल लीजिये. ऊपर से हरा धनियाँ डाल कर सजा दीजिये.  अलग से प्याले में बीकानेरी सेव रखिये.  पोहा प्लेट में डालिये, ऊपर से  बीकानेरी सेव डाल कर परोसिये और खाइये.")
else:
    print("Sorry item not present in Data:)\n")
    print("Try searching one of these\n........................\n")
    
    l=['Jeera rice','Tea','Poha','Mangodi','Pata gobhi','Dum aloo','Sev tamatar','Dosa','Bhindi','Rasgulla','Kheer','Chilli paneer','Paneer pakode','Rajma','Mutter paneer']
    print(l)